spring:
  application:
    name: inventory-management-system

  datasource:
    url: jdbc:postgresql://localhost:5432/inventory_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  task:
    execution:
      pool:
        core-size: 5
        max-size: 10
        queue-capacity: 100

server:
  port: 8080
  servlet:
    context-path: /api

jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  expiration: 86400000 # 24 hours in milliseconds

logging:
  level:
    com.inventory: DEBUG
    org.springframework.security: DEBUG
